### ISSUE TITLE
Properties addition?

### ISSUE THREAD

**Issue by PetarBegovic1701** [slorenzo/react-stopwatch#4]
Could you implement an autoStart feature as a bool?
Just to add on the whole package, it's really light and simple, thanks for the contribution.

**Comment by slorenzo** [comment]
Hi @PetarBegovic1701. 
I don't have time to add this feature. But, of course, I will do it later.
It is a good feature to this package.

**Comment by slorenzo** [comment]
https://github.com/slorenzo/react-stopwatch/commit/24808d0de35b85f75dc8453c93d20c2f6fd88c7b
