### ISSUE TITLE
Limit Should Be Inclusive

### ISSUE THREAD

**Issue by micodel** [slorenzo/react-stopwatch#7]
As a user, I would expect the limit to be inclusive. A limit of 10 seconds should be able to count to 10, not to 9.

In your example you have a limit of 10 seconds and loop = true, but when the clock hits 9 seconds it resets.

The limit should be inclusive, and/or the looping logic should display the limit before reseting. (i.e. loop when greater than limit not equal to).

**Comment by slorenzo** [comment]
Ey @micodel, you are right!
Will look into this.

**Comment by slorenzo** [comment]
https://github.com/slorenzo/react-stopwatch/commit/3916cf2741abee01be16b8323ce18aa3a44f36e4
